config/routes.rb
Rails.application.routes.draw do
  resources :recommendations

  devise_for :users
  get 'home/index'

root 'recommendations#index'

  get 'mymovies' => 'home#mymovies'
  get 'yourpicks' => 'recommendations#yourpicks'

end

app/models/recommendation.rb
class Recommendation < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :recommendations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

#Makes sure devise can see the new fields added to the model, came from this link: https://teamtreehouse.com/forum/strongparameters-and-treebook
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name << :last_name
    devise_parameter_sanitizer.for(:account_update) << :first_name << :last_name
  end
  def set_config
  	@configuration = Tmdb::Configuration.new
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:mymovies]
  def index
  end
  def mymovies
  end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  before_action :set_recommendation, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :new,:index]


  # GET /recommendations
  # GET /recommendations.json
  def index
    @recommendations = Recommendation.all
  end

  # GET /recommendations/1
  # GET /recommendations/1.json
  def show
  end

  # GET /recommendations/new
  def new
    @recommendation = Recommendation.new
    @popular_movies = ::Tmdb::Movie.popular
  end

  # GET /recommendations/1/edit
  def edit
  end

  # POST /recommendations
  # POST /recommendations.json
  def create
    @recommendation = Recommendation.new(recommendation_params)
    respond_to do |format|
      if @recommendation.save
        format.html { redirect_to @recommendation, notice: 'Recommendation was successfully created.' }
        format.json { render :show, status: :created, location: @recommendation }
      else
        format.html { render :new }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    current_user.recommendations.append(@recommendation)
    end
  end

  # PATCH/PUT /recommendations/1
  # PATCH/PUT /recommendations/1.json
  def update
    respond_to do |format|
      if @recommendation.update(recommendation_params)
        format.html { redirect_to @recommendation, notice: 'Recommendation was successfully updated.' }
        format.json { render :show, status: :ok, location: @recommendation }
      else
        format.html { render :edit }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end
  def yourpicks
  	@recommendations = Recommendation.all
  end
  # DELETE /recommendations/1
  # DELETE /recommendations/1.json
  def destroy
    @recommendation.destroy
    respond_to do |format|
      format.html { redirect_to recommendations_url, notice: 'Recommendation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recommendation
      @recommendation = Recommendation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recommendation_params
      params.require(:recommendation).permit(:title, :genre, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/views/home/index.html.erb
<h1>Hello World!</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/mymovies.html.erb
<p>
  My super secret movies.
</p>

app/views/layouts/_nav.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-3 nopadding"><%= link_to(image_tag('logo.png', :class => "img-responsive logo"),"/") %></div>
		<div class="col-md-9 nopadding">
			<div class="navbar navbar-default">

				  <div class="navbar-header">
				    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
				      <span class="icon-bar"></span>
				      <span class="icon-bar"></span>
				      <span class="icon-bar"></span>
				    </button>
				  </div>
				  <div class="navbar-collapse collapse navbar-responsive-collapse">
				    <ul class="nav navbar-nav">
				      <li class="active"><%= link_to("Movie Board", "/") %></li>

				    </ul>
				    <ul class="nav navbar-nav navbar-right">
				      <li><% if user_signed_in? %> <strong class="login-status">Hello, <%= current_user.first_name %>.</strong></li>
				      <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
				      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %><% else %><%= link_to "Sign up", new_user_registration_path %></li>
				       <li><%= link_to "Login", new_user_session_path %></li>
				    <% end %>
				    </ul>
				  </div>

			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Movieq</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <%= render "layouts/nav" %>
  </header>
<div class="container notices">
	<p class="notice"><%= notice %></p>
	<p class="alert" ><%= alert %></p>
</div>
<div class="container">
  <%= yield %>
<footer>
</footer>
</div>

</body>
</html>

app/views/recommendations/_form.html.erb
<%= form_for(@recommendation) do |f| %>
  <% if @recommendation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recommendation.errors.count, "error") %> prohibited this recommendation from being saved:</h2>

      <ul>
      <% @recommendation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit :value => "Add a Movie", class: "btn btn-success" %>
  </div>
<% end %>

app/views/recommendations/edit.html.erb
<h1>Editing recommendation</h1>

<%= render 'form' %>

<%= link_to 'Show', @recommendation %> |
<%= link_to 'Back', recommendations_path %>

app/views/recommendations/index.html.erb
	<h1 class="movieboard-header">Movie Board</h1> <%= link_to 'Add a Movie', new_recommendation_path, class: "btn btn-success movieboard-button"%>
	<table class="table table-hover">
	  <thead>
	    <tr>
	      <th>Movie Title</th>

	      <th>Added By</th>
	      <th colspan="3"></th>
	    </tr>
	  </thead>

	  <tbody>
	    <% @recommendations.each do |recommendation| %>
	      <tr>
	        <td><%= recommendation.title.camelize %></td>
	        <td><%= recommendation.user.first_name %> <%= recommendation.user.last_name %></td>
	        <td class="controls"><%= link_to 'Show', recommendation, class: "btn btn-primary btn-sm" %></td>
	        <td class="controls"><%= link_to 'Edit', edit_recommendation_path(recommendation), class: "btn btn-info btn-sm" %></td>
	        <td class="controls"><%= link_to 'Remove', recommendation, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>

app/views/recommendations/new.html.erb
<div class="row">
	<div class="col-md-6">
		<h1>Select a movie</h1>
				<% @popular_movies.first(15).each do |movie| %>

			<div class="movie_image">
			<%= link_to image_tag("http://image.tmdb.org/t/p/w154/#{movie['poster_path']}"), recommendations_path(

			"recommendation[title]" => movie["title"]

			), method: :post %>

			</a>
			</div>
				<% end %>
	</div>
	<div class="col-md-6">
		<h1>Or add our own.</h1>

		<%= render 'form' %>

		<%= link_to 'Back', recommendations_path %>
	</div>
</div>

app/views/recommendations/show.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<p>

		  <h2>Title: <span style="color:white;"><%= @recommendation.title.camelize %></span></h2>
		  <h3></h3>
		</p>
<%= link_to 'Edit', edit_recommendation_path(@recommendation) %> |
<%= link_to 'Back to All Recomendations', recommendations_path %>

	</div>
</div>

app/views/recommendations/yourpicks.html.erb
<h1 class="movieboard-header">Movie Board</h1> <%= link_to 'Add a Movie', new_recommendation_path, class: "btn btn-success movieboard-button"%>
	<table class="table table-hover">
	  <thead>
	    <tr>
	      <th>Movie Title</th>
	      <th>Genre</th>
	      <th>Added By</th>
	      <th colspan="3"></th>
	    </tr>
	  </thead>

 <tbody>
	    <% @recommendations.each do |recommendation| %>
	      <tr>
	        <td><%= recommendation.title %></td>
	        <td><%= recommendation.genre %></td>
	        <td><%= recommendation.user.first_name %> <%= recommendation.user.last_name %></td>
	        <td class="controls"><%= link_to 'Show', recommendation, class: "btn btn-primary btn-sm" %></td>
	        <td class="controls"><%= link_to 'Edit', edit_recommendation_path(recommendation), class: "btn btn-info btn-sm" %></td>
	        <td class="controls"><%= link_to 'Remove', recommendation, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>